### PR TITLE
Compatibility handle with Symfony 2 and 3

### PR DESCRIPTION
**Pull request by chadyred**
Compatibility handle with Symfony 2 and 3

### CODE REVIEW

**Comment by chadyred** [comment]
Test without success, it stay not a lot of change, juste the container access maybe to inject ;)

**Comment by fkrauthan** [comment]
@chadyred so you are saying you tried out the code change and it is not working?

**Comment by chadyred** [comment]
Yes, it's that, it's a beginning, but I  will plan to switch to gulp. What I've done is to change this 

```
  if ( $this->kernel->getContainer()->has('request_stack')) {
                    
                     $request = $this->kernel->getContainer()->get('request_stack')->getCurrentRequest();
                     
                } elseif (method_exists($this->container, 'isScopeActive') && $this->container->isScopeActive('request')) {
                    
                     $request = $this->kernel->getContainer()->get('request');
                     
                }
                
                if (substr($request->getBaseUrl(),
```

It's a simple compatibilité with the new access to request service.

**Comment by chadyred** [comment]
It stays just a little bit things to do, I quickly change that, it's a simple change from Symfony 2 to 3.

It's important to maintain your bundle because assetic **return an error which indicate your version is too old( the request call).**

**Comment by lmerotta** [comment]
@chadyred any updates on this ? I plan to use your bundle on Symfony 2.8 (and 3.x later), should I wait for this to be merged, or should I fork this repo ?

**Comment by fkrauthan** [comment]
Hey sorry for the delay I am working on it now.

**Pull request merged**
